### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by DiegoRRR** [layerdiffusion/sd-forge-layerdiffuse#131]
I just installed it and I have this problem. For some reason it doesn't find its own temporary file:

```
[Memory Management] Target: JointTextEncoder, Free GPU: 11149.60 MB, Model Requi
re: 234.72 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remain
ing: 9890.88 MB, All loaded to GPU.
Moving model(s) has taken 0.11 seconds
[Unload] Trying to free 1024.00 MB for cuda:0 with 1 models keep loaded ... Curr
ent free memory is 10468.56 MB ... Done.
[LayerDiffuse] LayerMethod.FG_ONLY_ATTN_SD15
[Unload] Trying to free 3155.23 MB for cuda:0 with 0 models keep loaded ... Curr
ent free memory is 10468.26 MB ... Done.
[Memory Management] Target: KModel, Free GPU: 10468.26 MB, Model Require: 1639.4
1 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 7804
.85 MB, All loaded to GPU.
Moving model(s) has taken 0.63 seconds
100%|██████████████████████████████████████████| 20/20 [00:10<00:00,  1.84it/s]
[Unload] Trying to free 1568.67 MB for cuda:0 with 0 models keep loaded ... Curr
ent free memory is 8359.66 MB ... Done.
[Memory Management] Target: IntegratedAutoencoderKL, Free GPU: 8359.66 MB, Model
 Require: 159.56 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB,
Remaining: 7176.10 MB, All loaded to GPU.
Moving model(s) has taken 0.20 seconds
[Unload] Trying to free 1282.13 MB for cuda:0 with 0 models keep loaded ... Curr
ent free memory is 8198.67 MB ... Done.
[Memory Management] Target: UNet1024, Free GPU: 8198.67 MB, Model Require: 198.5
6 MB, Previously Loaded: 0.00 MB, Inference Require: 1024.00 MB, Remaining: 6976
.10 MB, All loaded to GPU.
Moving model(s) has taken 0.12 seconds
100%|████████████████████████████████████████████| 8/8 [00:01<00:00,  6.92it/s]
Total progress: 100%|██████████████████████████| 20/20 [00:11<00:00,  1.72it/s]
Traceback (most recent call last):█████████████| 20/20 [00:11<00:00,  2.13it/s]
  File "D:\apps\stable-diffusion\Forge_2024\system\python\lib\site-packages\grad
io\queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "D:\apps\stable-diffusion\Forge_2024\system\python\lib\site-packages\grad
io\route_utils.py", line 285, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\apps\stable-diffusion\Forge_2024\system\python\lib\site-packages\grad
io\blocks.py", line 1933, in process_api
    data = await self.postprocess_data(block_fn, result["prediction"], state)
  File "D:\apps\stable-diffusion\Forge_2024\system\python\lib\site-packages\grad
io\blocks.py", line 1756, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "D:\apps\stable-diffusion\Forge_2024\system\python\lib\site-packages\grad
io\components\gallery.py", line 235, in postprocess
    for o in executor.map(_save, value):
  File "concurrent\futures\_base.py", line 621, in result_iterator
  File "concurrent\futures\_base.py", line 319, in _result_or_cancel
  File "concurrent\futures\_base.py", line 451, in result
  File "concurrent\futures\_base.py", line 403, in __get_result
  File "concurrent\futures\thread.py", line 58, in run
  File "D:\apps\stable-diffusion\Forge_2024\system\python\lib\site-packages\grad
io\components\gallery.py", line 208, in _save
    file = processing_utils.save_pil_to_cache(
  File "D:\apps\stable-diffusion\Forge_2024\webui\modules\ui_tempdir.py", line 6
6, in save_pil_to_file
    file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)

  File "tempfile.py", line 559, in NamedTemporaryFile
  File "tempfile.py", line 556, in opener
  File "tempfile.py", line 256, in _mkstemp_inner
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\apps\\stable-diffus
ion\\Forge_2024\\webui\\output\\txt2img-images\\tmpvyefum4a.png'

```

**Comment by DiegoRRR** [comment]
Oops, my bad, it was a bad setting in "saving images/grids" "Directory for temporary images;" at the bottom, I had "output" instead of "outputs", missing a "s".
