### ISSUE TITLE
layerdiffusion doesn't show up

### ISSUE THREAD

**Issue by mertayd0** [layerdiffusion/sd-forge-layerdiffuse#15]
I just installed it but can't see any section for layerdiffusion on a1111, what's wrong?

**Comment by carlmoss22** [comment]
me too. i can't see any tabs called layerdiffusion.

**Comment by zombrax1** [comment]
yes i get same issue so i checked my cmd  i found this errors may give a hint 

`Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  10217.1826171875
[Memory Management] Model Memory (MB) =  2144.3546981811523
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  7048.827919006348
Moving model(s) has taken 0.76 seconds
Model loaded in 37.6s (load weights from disk: 1.3s, forge instantiate config: 1.4s, forge load real models: 33.4s, calculate empty prompt: 1.5s).
[Layer Diffusion] LayerMethod.FG_ONLY_ATTN
*** Error running process_before_every_sampling: C:\Users\user\Desktop\webui_forge_cu121_torch21\webui\extensions\sd-forge-layerdiffusion\scripts\forge_layerdiffusion.py
    Traceback (most recent call last):
      File "C:\Users\user\Desktop\webui_forge_cu121_torch21\webui\modules\scripts.py", line 835, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "C:\Users\user\Desktop\webui_forge_cu121_torch21\webui\extensions\sd-forge-layerdiffusion\scripts\forge_layerdiffusion.py", line 139, in process_before_every_sampling
        vae_transparent_decoder = TransparentVAEDecoder(load_torch_file(model_path))
      File "C:\Users\user\Desktop\webui_forge_cu121_torch21\webui\extensions\sd-forge-layerdiffusion\lib_layerdiffusion\models.py", line 192, in __init__
        model = UNet1024(in_channels=3, out_channels=4)
      File "C:\Users\user\Desktop\webui_forge_cu121_torch21\system\python\lib\site-packages\diffusers\configuration_utils.py", line 611, in inner_init
        init(self, *args, **init_kwargs)
      File "C:\Users\user\Desktop\webui_forge_cu121_torch21\webui\extensions\sd-forge-layerdiffusion\lib_layerdiffusion\models.py", line 89, in __init__
        down_block = get_down_block(
    TypeError: get_down_block() got an unexpected keyword argument 'attention_head_dim'
`

**Comment by mattmin45** [comment]
Same here. Tried to delete and  install manually or activate then restart - reactivate and restart but no changes. 

Here's the error that I get from A1111's start :

```
*** Error loading script: forge_layerdiffusion.py
    Traceback (most recent call last):
      File "C:\AI\A1111\stable-diffusion-webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\AI\A1111\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\AI\A1111\stable-diffusion-webui\extensions\sd-forge-layerdiffuse-main\scripts\forge_layerdiffusion.py", line 11, in <module>
        from lib_layerdiffusion.utils import rgba2rgbfp32, to255unit8, crop_and_resize_image, forge_clip_encode
      File "C:\AI\A1111\stable-diffusion-webui\extensions\sd-forge-layerdiffuse-main\lib_layerdiffusion\utils.py", line 3, in <module>
        from ldm_patched.modules import model_management
    ModuleNotFoundError: No module named 'ldm_patched'
```

**Comment by chieeo** [comment]
![image](https://github.com/layerdiffusion/sd-forge-layerdiffuse/assets/159146308/e3dc5616-0bb6-4214-a4f9-4314d68d12b1)
I installed forge and I got an error when I checked layer diffusion
