### ISSUE TITLE
AttributeError: 'VAE' object has no attribute 'clone'   Forge LayerDiffusion

### ISSUE THREAD

**Issue by Mikk702** [layerdiffusion/sd-forge-layerdiffuse#39]
Everything seems to be loaded fine, but I dont get the transparency. Everything seems updated from the extensions/updates tab.
Any help is appreciated. error:

*** Error running process_before_every_sampling: D:\Ai\stable-diffusion-webui-forge-main\extensions\sd-forge-layerdiffusion\scripts\forge_layerdiffusion.py
    Traceback (most recent call last):
      File "D:\Ai\stable-diffusion-webui-forge-main\modules\scripts.py", line 835, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\Ai\stable-diffusion-webui-forge-main\extensions\sd-forge-layerdiffusion\scripts\forge_layerdiffusion.py", line 130, in process_before_every_sampling
        vae = p.sd_model.forge_objects.vae.clone()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    AttributeError: 'VAE' object has no attribute 'clone'

**Comment by giovanith** [comment]
same error here...

**Comment by Mikk702** [comment]
ok  I figured it out. Apparently forge was installed wrong. I re-installed. in my case:   D:/Ai/   git clone  sd forge url from github
then in that top directory do a git pull. Then I copied all the necessary models from the bad install to the new install models/layer models. Then I installed from layerdiffusion git url in 'extension/install from url' in forge. I ran it with juggernaut 9 and i got the two little thumbnails at the bottom which means it worked.  I wasted a whole day messing with it but it was a learning process. I hope this helps.

**Comment by UnirionGames** [comment]
same here

**Comment by nyukers** [comment]
[Layer Diffusion] LayerMethod.FG_ONLY_ATTN
*** Error running process_before_every_sampling: D:\SDForge\webui\extensions\sd-forge-layerdiffuse\scripts\forge_layerdiffusion.py
    Traceback (most recent call last):
      File "D:\SDForge\webui\modules\scripts.py", line 830, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "D:\SDForge\webui\extensions\sd-forge-layerdiffuse\scripts\forge_layerdiffusion.py", line 151, in process_before_every_sampling
        vae = p.sd_model.forge_objects.vae.clone()
    AttributeError: 'VAE' object has no attribute 'clone'

**Comment by nyukers** [comment]
> re-installed

Reinstalling Forge due to one extension? It's bad decision!

**Comment by nyukers** [comment]
> > re-installed
> 
> Reinstalling Forge due to one extension? It's bad decision!

Fixed by Forge update.
