### ISSUE TITLE
安装后在WEBUI里看不到这个插件

### ISSUE THREAD

**Issue by lzhfdwu007** [layerdiffusion/sd-forge-layerdiffuse#43]
WEBUI里看不到这个插件，终端提示错误代码为
Tag Autocomplete: Could not locate model-keyword extension, Lora trigger word completion will be limited to those added through the extra networks menu.
*** Error loading script: forge_layerdiffusion.py
    Traceback (most recent call last):
      File "D:\sd-webui-aki-v4.4\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\sd-webui-aki-v4.4\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\sd-webui-aki-v4.4\extensions\sd-forge-layerdiffuse\scripts\forge_layerdiffusion.py", line 14, in <module>
        from ldm_patched.modules.utils import load_torch_file
    ModuleNotFoundError: No module named 'ldm_patched'

**Comment by ClaudeFANN** [comment]
我也是 用的秋叶整合包

**Comment by Carlofkl** [comment]
same question

**Comment by sljjyy** [comment]
+1

**Comment by Haoming02** [comment]
這個插件只能在 [Forge](https://github.com/lllyasviel/stable-diffusion-webui-forge) 上使用，並不支援 [Automatic1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui) (或衍伸的整合包)

**Comment by kinaito** [comment]
只能等sd的版本了

**Comment by chieeo** [comment]
我安装了forge，但是依然无法加载layer diffusion。
![image](https://github.com/layerdiffusion/sd-forge-layerdiffuse/assets/159146308/fb948d56-8d36-471c-9c1c-577dfff9ff66)

**Comment by rootgrandfather** [comment]
how to solve?
