### ISSUE TITLE
Error processing every sampling

### ISSUE THREAD

**Issue by TanvirHafiz** [layerdiffusion/sd-forge-layerdiffuse#72]
I get this

Moving model(s) skipped. Freeing memory has taken 1.48 seconds
[Layer Diffusion] LayerMethod.FG_ONLY_ATTN_SD15
*** Error running process_before_every_sampling: F:\stable-diffusion-webui-forge\extensions\sd-forge-layerdiffuse\scripts\forge_layerdiffusion.py
    Traceback (most recent call last):
      File "F:\stable-diffusion-webui-forge\modules\scripts.py", line 830, in process_before_every_sampling
        script.process_before_every_sampling(p, *script_args, **kwargs)
      File "F:\stable-diffusion-webui-forge\extensions\sd-forge-layerdiffuse\scripts\forge_layerdiffusion.py", line 151, in process_before_every_sampling
        vae = p.sd_model.forge_objects.vae.clone()
    AttributeError: 'VAE' object has no attribute 'clone'

plus no model is downloaded. trying to generate in SD1.5. I manually downloaded the model and still issues.

**Comment by Paramortis** [comment]
I have the exact same problem, any help to fix this would be appreciated.

**Comment by unsignedzhang** [comment]
I have the same problem today, and fix it by updating webui and layerdiffusion.

**Comment by atbgams** [comment]
I have the exact same problem while using ip-adapter-faceid-plusv2_sdxl,but no problem while using other controlnet
