### ISSUE TITLE
Error loading script.

### ISSUE THREAD

**Issue by Astelteyn** [layerdiffusion/sd-forge-layerdiffuse#85]
*** Error loading script: forge_layerdiffusion.py
    Traceback (most recent call last):
      File "E:\Stable Diffusion\stable-diffusion-webui\modules\scripts.py", line 527, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Stable Diffusion\stable-diffusion-webui\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-forge-layerdiffuse\scripts\forge_layerdiffusion.py", line 11, in <module>
        from lib_layerdiffusion.utils import rgba2rgbfp32, to255unit8, crop_and_resize_image, forge_clip_encode
      File "E:\Stable Diffusion\stable-diffusion-webui\extensions\sd-forge-layerdiffuse\lib_layerdiffusion\utils.py", line 3, in <module>
        from ldm_patched.modules import model_management
    ModuleNotFoundError: No module named 'ldm_patched'

**Comment by Astelteyn** [comment]
download models in layer_model not work

**Comment by Astelteyn** [comment]
torch: 2.1.2+cu121

**Comment by Astelteyn** [comment]
It adpt for a1111 or not?

**Comment by Conferno01** [comment]
I have the same error

**Comment by Casacb** [comment]
I have the same error

**Comment by fl0wm0ti0n** [comment]
i have the same error
