### ISSUE TITLE
No module named 'ldm_patched'

### ISSUE THREAD

**Issue by 158zd** [layerdiffusion/sd-forge-layerdiffuse#98]
Error loading script: forge_layerdiffusion.py
    Traceback (most recent call last):
      File "D:\ai\stable-diffusion-webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\ai\stable-diffusion-webui\modules\script_loading.py", line 14, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\ai\stable-diffusion-webui\extensions\sd-forge-layerdiffuse\scripts\forge_layerdiffusion.py", line 11, in <module>
        from lib_layerdiffusion.utils import rgba2rgbfp32, to255unit8, crop_and_resize_image, forge_clip_encode
      File "D:\ai\stable-diffusion-webui\extensions\sd-forge-layerdiffuse\lib_layerdiffusion\utils.py", line 3, in <module>
        from ldm_patched.modules import model_management
    ModuleNotFoundError: No module named 'ldm_patched'

**Comment by jetjodh** [comment]
This does not work with A1111. You gotta use Forge UI.
